[tool.poetry]
name = "ai_agent_project"
version = "0.1.0"
description = "Comparsion of the free open source available LLm model and OPENAI's paid LLM model for the ai agentic development"
authors = ["hariharan gopinath"]


[tool.ruff]
line-length = 100
select = ["E", "F", "W", "I"] # Example rule sets
# Add other configurations as needed


[tool.poetry.dependencies]
python = ">=3.10,<4.0"
pytest = "^8.3.4"
ruff = "^0.4.4" # Using a recent version of Ruff
phi
yfinance
groq

